# How to produce rules automatically

# Use:
# make -f 80_automation.mk USE=explicit
# Expect: All targets are produced
# make -f 80_automation.mk clean

# make -f 80_automation.mk USE=pattern
# Expect: All targets are produced
# make -f 80_automation.mk clean

# make -f 80_automation.mk USE=canned-recipe
# Expect: All targets are produced
# make -f 80_automation.mk clean

# make -f 80_automation.mk USE=one-line-one-by-one
# Expect: All targets are produced
# make -f 80_automation.mk clean

# make -f 80_automation.mk USE=one-line-loop
# Expect: Make fails to generate recipes in function context.
# make -f 80_automation.mk clean

# make -f 80_automation.mk USE=call
# Expect: Make fails to generate recipes in function context.

# make -f 80_automation.mk USE=eval
# Expect: All targets are produced
# make -f 80_automation.mk clean

# See: https://www.gnu.org/software/make/manual/html_node/Canned-Recipes.html#index-canned-recipes

targets ::= file1 file2 file3

.PHONY: all
all: $(targets)

USE ?= explicit
ifeq (explicit,$(USE))
$(info All rules are defined explicitly.)

file1:
	@echo "Running rule file1"
	touch file1
	@echo "Every line uses a separate shell pid=$$$$"
	@echo "Every line uses a separate shell pid=$$$$"
file2:
	@echo "Running rule file2"
	touch file2
	@echo "Every line uses a separate shell pid=$$$$"
	@echo "Every line uses a separate shell pid=$$$$"
file3:
	@echo "Running rule file3"
	touch file3
	@echo "Every line uses a separate shell pid=$$$$"
	@echo "Every line uses a separate shell pid=$$$$"

else ifeq (pattern,$(USE))
$(info Define a static pattern rule for all targets.)

$(targets): %:
	@echo "Running rule $@"
	touch $@
	@echo "Every line uses a separate shell pid=$$$$"
	@echo "Every line uses a separate shell pid=$$$$"

else ifeq (canned-recipe,$(USE))
$(info Rules using a canned recipe)

define recipe
@echo "Running rule $@"
touch $@
@echo "Every line uses a separate shell pid=$$$$"
@echo "Every line uses a separate shell pid=$$$$"
endef

$(targets): %:
	$(recipe)

else ifeq (one-line-one-by-one,$(USE))
$(info Define a one line rule as macro and expand one rule in a line.)

rule = $1: ; @echo "Running rule $1"; touch $1; echo "shell pid is pid=$$$$$$$$"
$(call rule,file1)
$(call rule,file2)
$(call rule,file3)

else ifeq (one-line-loop,$(USE))
$(info Define a one line rule as macro and expand one rule in a function loop.)
$(warning Error is expected.)

define nl


endef
rule = $1: ; echo "Running rule $1"; touch $1; echo "shell pid is pid=$$$$$$$$"$(nl)
# But no such thing:
$(foreach target,$(targets),$(call rule,$(target)))

else ifeq (call,$(USE))
$(info Multiple line rules generated by a function call.)
$(warning Error is expected.)

define rule
$(1):
	@echo "Running rule $@"
	touch $@
	@echo "Every line uses a separate shell pid=$$$$"
	@echo "Every line uses a separate shell pid=$$$$"
endef
# target and prerequisites are not properly parsed in function context
$(foreach target,$(targets),$(call rule,$(target)))
# *** multiple target patterns.  Stop.

else ifeq (eval,$(USE))
$(info Rules generated by eval in a function loop.)

define rule2
$(target):
	@echo "Running rule $$@"
	touch $$@
	@echo "Every line uses a separate shell pid=$$$$$$$$"
	@echo "Every line uses a separate shell pid=$$$$$$$$"
endef
$(foreach target,$(targets),$(eval $(rule2)))

else
$(error Wrong value for USE - must be recipe|call|eval but is '$(USE)')

endif

.PHONY: clean
clean:;rm -f $(targets)
